"""Webapp helpers for price-platform."""

from .app_factory import (
    BlueprintRegistration,
    CommonRoutesSettings,
    OptionalBlueprintRegistration,
    PlatformAppSpec,
    SeoRoutesSpec,
    StandardPlatformAppSpec,
    WebAppSettings,
    configure_app,
    create_app,
    create_configured_platform_app,
    create_platform_app,
    create_standard_platform_spec,
    create_warmup,
    finalize_platform_app,
    install_common_routes,
    install_seo_routes,
    notify_content_update,
    register_blueprints,
    register_optional_blueprints,
)
from .cors import extract_origin, get_cors_origins, is_allowed_request_origin
from .dependencies import (
    AppDependencies,
    AppServices,
    WebApiContext,
    WebApiDependencySpec,
    build_app_dependencies,
    build_app_services,
    build_webapi_context,
    build_webapi_dependencies,
    get_dependencies,
    get_typed_dependencies,
    get_webapi_config,
    get_webapi_dependencies,
    get_webapi_services,
    install_dependencies,
    install_webapi_dependencies,
)
from .headers import CacheRule, apply_common_headers
from .request_context import SupportsRequestConnection, install_request_hooks
from .runtime_memory_routes import SupportsMemorySnapshot, install_runtime_memory_routes

__all__ = [
    "AppDependencies",
    "AppServices",
    "BlueprintRegistration",
    "CacheRule",
    "CommonRoutesSettings",
    "OptionalBlueprintRegistration",
    "PlatformAppSpec",
    "SeoRoutesSpec",
    "StandardPlatformAppSpec",
    "SupportsMemorySnapshot",
    "SupportsRequestConnection",
    "WebApiContext",
    "WebApiDependencySpec",
    "WebAppSettings",
    "apply_common_headers",
    "build_app_dependencies",
    "build_app_services",
    "build_webapi_context",
    "build_webapi_dependencies",
    "configure_app",
    "create_app",
    "create_configured_platform_app",
    "create_platform_app",
    "create_standard_platform_spec",
    "create_warmup",
    "extract_origin",
    "finalize_platform_app",
    "get_cors_origins",
    "get_dependencies",
    "get_typed_dependencies",
    "get_webapi_config",
    "get_webapi_dependencies",
    "get_webapi_services",
    "install_common_routes",
    "install_dependencies",
    "install_request_hooks",
    "install_runtime_memory_routes",
    "install_seo_routes",
    "install_webapi_dependencies",
    "is_allowed_request_origin",
    "notify_content_update",
    "register_blueprints",
    "register_optional_blueprints",
]
